### ISSUE TITLE
Folge 1 - Stand der Kunst: Programmiersprachen

### ISSUE THREAD

**Issue by mknet** [softmensch/podcast#1]
1. Vorstellung
2. Arten der Programmiersprachen, statisch und dynamisch typisiert, interpretiert und kompiliet
3. Einsatzgebiete

Ziele:
    - Etwas haben, worüber wir sicher was zu sagen haben
    - Leute für unsere Art über dinge zu sprechen zu begeistern
    - Leute abholen, indem man dinge aufgreift, die sie kennen

Mehrwert:
    - Angesprochen fühlen
    - Angenehm zum zuhören, leute abholen
    - Warum ist es eine gute ideem x zu verwenden
    - Warum Go vs Rust keinen Sinn ergibt
    - Was sich lohnt, anzuschauen

## Vorstellung/Intro

"Software und Menschen der Podcast"
Folgennummer
Titel/Thema

Jingle 1

Wir beide, Gäste
Bei Gast, Frage/Überleitung an Gast

2Sätze vom Gast 

Jingle 2

Los gehts 

Folge

## Arten der Programmiersprachen
- statisch und dynamisch typisiert
- interpretiert und kompliliert
- Auszeichnungssprachen (HTML, XML, YML)

## Abgrenzung
- Dinge auf die wir nicht eingehen
  - Spezialisierte Sprachen (Beispiele, ABAP, TLA+, ADA)

## Einsatzgebiete
Einmal alle durchgehen
Erst bei der behandlung die definition/eigenschaften der kategorie erwähnen und erklären

### Webapp
- Java
- Kotlin
- Scala
- Groovy
- Javascript
- Typescript
- PHP
- Perl
- Go
- Python
- Ruby
- Elixir
- C#
- Rust

### Web Frontend
- Javascript
- Typescript
- Assemblyscript
- HTML
- CSS
- WASM

### Scripting
- Shell / Bash
- Python
- Powershell
- Go

### Embedded / System- oder Hardware-nah
- C
- C++
- Rust

### Analyse / Data Science
- R
- Julia
- Python
- Base SAS

### Proprietäre Sprachen
- VBA
- ABAP

## Shownotes

1. Scripting - ab 1:48:50
    1. Definition: Schnell geschrieben, kurz mal ausgeführt, schnell weg geworfen
    2. [Bash](https://de.wikipedia.org/wiki/Bash_(Shell)) oder [Shell](https://de.wikipedia.org/wiki/Shell_(Betriebssystem))
    3. [PowerShell](https://de.wikipedia.org/wiki/PowerShell) / [Batch](https://de.wikibooks.org/wiki/Batch-Programmierung:_Batch-Befehle)
    4. [Python](https://thinkinfi.com/python-scripting-tutorial-for-beginners/) ([Guter Einstieg in Python](https://de.wikibooks.org/wiki/Batch-Programmierung:_Batch-Befehle))
    5. [xz](https://github.com/google/zx) 
    6. [Go](https://go.dev)Wikipedia
    7. [Rust](https://www.rust-lang.org)
    8. [Groovy](http://www.groovy-lang.org) ([Wikipedia](https://en.wikipedia.org/wiki/Apache_Groovy))
    9. JavaScript
    10. PHP
    11. Ruby
2. Native Applikationen
    1. CLI
        1. Definition: Werden auf der Kommandozeile / Konsole / Terminal ausgeführt
        2. ls
        3. Bash Scripts
        4. lazy git
        5. Unterschiedliche Bedienung von Computern
    2. Desktop
        1. Welche Applikationen laufen bei uns aktuell?
            1. Studiolink
            2. Electron
            3. Fork
        2. Windows Forms
        3. GTK
        4. C++
        5. Objective-C
        6. TCL
        7. Perl
        8. Qt
        9. Rust-Bindings: Qt / GTK
        10. Java & Swing
        11. ELM-Architekur (@trimoq bitte Link ergänzen)
        12. [iced](https://github.com/iced-rs/iced) 
        13. Schöne Banking Software: [MoneyMoney](https://moneymoney-app.com)
        14. C#
        15. Electron
        16. Tauri
        17. WebAssembly
        18. [tmux](https://github.com/tmux/tmux/wiki)
        20. Terminal Multiplexer
        21. [zellij](https://github.com/zellij-org/zellij)
    3. mobile Applikationen
        1. Nostalgie
            1. Windows Phone
            2. FirefoxOS
            3. webOS
        2. Native Entwicklung
            1. iOS
               1. Xcode
               2. Objective-C
               3. Swift
            2. Android
                1. Kotlin
                2. Java
         3. Multiplattform-Entwicklung
             1. Flutter
             2. Dart
             3. AngularDart
             4. Cordova
             5. Ionic
             6. ReactNative, JavaScript & JSX
             7. Xamarin & C#
             8. C, C++, Rust, OpenGL, auf Android
             9. DalvikVM
             10. Zukunftsträchtig durch Rust, Flutter und C
             11. [Python und C](https://docs.python.org/3/extending/extending.html)
3. Embedded / eingebettete Systeme (ab 2:33:55)

**Comment by trimoq** [comment]
## Backend, Frontend, Systemnah, etc:
- Rust

## Backend:
- Elixir

**Comment by mknet** [comment]
> ## Backend, Frontend, Systemnah, etc:
> * Rust
> 
> ## Backend:
> * Elixir

@trimoq Ich hab das mal oben ergänzt. Passt das so für Dich?

**Comment by trimoq** [comment]
> @trimoq Ich hab das mal oben ergänzt. Passt das so für Dich?

auf jeden Fall

Ich würde auch die ganzen Nischen-Sprachen wie V, vala oder [rockstar](https://codewithrockstar.com/) garnicht aufnehmen, auch wenn es da draußen echt coole Sachen gibt.

Man könnte kurz erwähnen, dass es weitere general-purpose Sprachen gibt, die im podcast nicht weiter behandelt werden, wie Haskell, Ada oder Lua, da wir nur ein paar rausgepickt haben. 

Und man sollte erwähnen, dass es eine bazillion spezialisierte sprachen gibt wie TLA+, ABAP, BPMN und co
Außerdem sollten wir überlegen, wie stark wir Spezifikationssprachen und Auszeichnungssprachen von "echten" Programmiersprachen abgrenzen.

**Comment by mknet** [comment]
> > @trimoq Ich hab das mal oben ergänzt. Passt das so für Dich?
> 
> auf jeden Fall
> 
> Ich würde auch die ganzen Nischen-Sprachen wie V, vala oder [rockstar](https://codewithrockstar.com/) garnicht aufnehmen, auch wenn es da draußen echt coole Sachen gibt.
> 
> Man könnte kurz erwähnen, dass es weitere general-purpose Sprachen gibt, die im podcast nicht weiter behandelt werden, wie Haskell, Ada oder Lua, da wir nur ein paar rausgepickt haben.
> 
> Und man sollte erwähnen, dass es eine bazillion spezialisierte sprachen gibt wie TLA+, ABAP, BPMN und co Außerdem sollten wir überlegen, wie stark wir Spezifikationssprachen und Auszeichnungssprachen von "echten" Programmiersprachen abgrenzen.

Amen

**Comment by mknet** [comment]
Gescheitertes Experiment. Wir schließen dieses Issue zugunsten [einer neuen Folge](https://github.com/softmensch/podcast/issues/14).
